### ISSUE TITLE
suggestion: custom runtime storage path

### ISSUE THREAD

**Issue by elig0n** [darkhz/invidtui#11]

**Comment by darkhz** [comment]
Can you elaborate on why this feature should be implemented?

**Comment by elig0n** [comment]
Sure I used the app for awhile and now I found out that my home directory has several new unwanted files: config, state, playhistory.json & history.
I simply don't like having runtime/history files thrown around my home directory like that and that's not a normal behavior for most linux apps.
Most Linux programs store such persistent config/runtime files commonly in ~/.config/APPNAME ~/.local/share/APPNAME and ~/.cache

**Comment by darkhz** [comment]
Invidtui should be creating those files in a dedicated config directory (usually ~/.config/invidtui) by default. I wonder why it creates those files in your home directory. I agree, cluttering the home directory must not happen. Try reinstalling it once again and ensure that your ~/.config folder is writeable. I cannot reproduce this issue on my end, but I will have a look at it nevertheless.

**Comment by darkhz** [comment]
@elig0n does it still create files in your home directory after re-installation? Did you check whether your config directory is writable?

**Comment by elig0n** [comment]
It is writable and it did not aeem to do it again ever since then so I will be closing for now
