### ISSUE TITLE
scoop-package 

### ISSUE THREAD

**Issue by OmiChrome** [darkhz/invidtui#14]
man this invidTUi is gold 

it wokr well 

but only  thign is misisng is scoop pacakge to  make easer to install in window :)

**Comment by darkhz** [comment]
I suppose I would be open to publishing a scoop manifest. Once I get to a Windows/Powershell setup, I'll start creating and testing manifests, publish it once its done, and close this issue with the linked manifest. Alternatively, you could create a manifest and publish the link here, and I'll update it accordingly.

**Comment by OmiChrome** [comment]
oh thx for the work :O

**Comment by AyoungDukie** [comment]
Just an FYI, I did prepare (a basic) one for my own use; feel free to use as needed!

[invidtui.json](https://github.com/AyoungDukie/personal_bucket/blob/master/bucket/invidtui.json)

**Comment by darkhz** [comment]
@AyoungDukie thank you very much for this. Is it published in the scoop repos? If not, I think I can make some modifications to the file, like listing dependencies for example.

**Comment by AyoungDukie** [comment]
Currently it is not, I simply put it into a personal bucket where I keep/kept things that were not currently included in the main Scoop buckets

**Comment by darkhz** [comment]
@AyoungDukie ok, I think I will use this file, make some modifications and try submitting it to the main scoop repos.

**Comment by AyoungDukie** [comment]
Just wanted to point out that someone has made a much more thorough manifest, which would be a better baseline than mine (I am going to update mine to utilize their more detailed info).

https://github.com/Jadeiin/scoop/blob/master/bucket/invidtui.json

**Comment by darkhz** [comment]
Thank you, I will close this issue.
