### ISSUE TITLE
playing links with command line option 

### ISSUE THREAD

**Issue by Ovens-Syntax** [darkhz/invidtui#15]
Howdy i am writing to ask whether there is a way to play invidious links through a command line option and if there is not whether this will be implemented in the future sorry if this is a dumb question i know very little about software i looked on the wiki and could not find a way to do this i mean something like

invidtui --play https://invidious.snopyta.org/watch?v=example

ps. this program is really cool thanks for making it

**Comment by darkhz** [comment]
There currently isn't an option like that, but I'll add this in the next release

**Comment by Ovens-Syntax** [comment]
Alright thanks so much
