### ISSUE TITLE
save youtube playlist

### ISSUE THREAD

**Issue by ghost** [darkhz/invidtui#19]
iread the manuel but could not find a way to do it (generated from someone)

**Comment by darkhz** [comment]
If you mean the currently playing playlist, press p and then press Ctrl+S.

If you mean saving a playlist from the search results/playlist viewer/dashboard, that is not implemented yet. I'll add this to my TODO list.

**Comment by ghost** [comment]
I meant second one thanks!

**Comment by ghost** [comment]
@darkhz I also didn't want to open a separate issue so I thought I'd write here, I'm watching from invidtui, it's fine, the token is also registered, there is no problem there, but the problem is that it doesn't mark the following videos as watched, is there a solution?

**Comment by darkhz** [comment]
Hmm, to track if a video has been watched, invidious would need to store the data and would need to make said data query-able within the API, which looking at the docs, is not currently implemented. I suppose I could save the watch history locally, but I think saving data that way could be inconsistent, and you'd have to copy the history file across machines you need to access Invidious.

**Comment by ghost** [comment]
Oh i see it would be good but not that necessary, thanks for answer

**Comment by darkhz** [comment]
@toprak   Just to be clear, do you mean downloading and saving all the videos in a playlist, or just saving playlist entries in a playlist file?

**Comment by ghost** [comment]
@darkhz 
> or just saving playlist entries in a playlist file?

this

**Comment by darkhz** [comment]
This has now been implemented, please see the release notes on how to use this feature.
