### ISSUE TITLE
Provide binaries to quickly try this out

### ISSUE THREAD

**Issue by sudipghimire533** [darkhz/invidtui#2]
I want to try invidtui but I don't want to build from source as I do not have Go installed and currently can go that way ( I am running out of disk :wink: ). So maybe write an action to keep releasing the master branch. Ping me if you need help. I will surely help if I find some time.

I really wanted to give it a try as I am also working in similar project here: https://github.com/sudipghimire533/ytui-music

I am also using same stack, invidious, mpv, youtube-dl tui and stuff.

Best of lock :+1:

**Comment by darkhz** [comment]
You can download binaries from the release page, no need to build from source.

**Comment by sudipghimire533** [comment]
Oops! Was release section vanished for that hour I was visiting in? lol. Thank you :)
