### ISSUE TITLE
Videos of channel not displayed

### ISSUE THREAD

**Issue by robert-groensfeld** [darkhz/invidtui#20]
In my search results the channels all have 0 videos. Videos are also missing in the videos tab of the channel view.
![0-vids-chan](https://user-images.githubusercontent.com/20993746/224562194-5048e628-654b-452f-afc6-49e359133d89.png)
![0-vids-search](https://user-images.githubusercontent.com/20993746/224562195-83d05f6f-7e90-4969-8ce2-4bcf9b492062.png)

**Comment by darkhz** [comment]
Hmm, seems like something's changed with Invidious. I'll take a look.
