### ISSUE TITLE
No help on key bindings

### ISSUE THREAD

**Issue by robert-groensfeld** [darkhz/invidtui#21]
It would be nice to have a page with at least the most important key bindings in the application.

**Comment by darkhz** [comment]
Yes. I'm currently working on a rewrite of the application, which will include a menu feature **with** keybindings listed for ease of use.

**Comment by robert-groensfeld** [comment]
Does it make sense to contribute while you are rewriting?

**Comment by darkhz** [comment]
That would take too much effort, I'm afraid, since I'm restructuring the entire codebase. It would help if you could file a PR, but I doubt whether you could make sense of the codebase, as messy as it is.

**Comment by darkhz** [comment]
Most keybindings are context based, and as such, simply posting the keybindings would confuse the user. I have written the wiki to remedy this, but again it was confusing for some users. As a result, I have now introduced a menu bar with various menu options, which lists the keybinding for each operation. Do have a look at it and see whether it would suffice.
