### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by robert-groensfeld** [darkhz/invidtui#23]
Add a man page with detailed description of every option from the wiki. 

Btw: when I piped the `--help` output to `less` the search and scrolling were broken.

**Comment by enzv** [comment]
Unix man pages are not [strongly recommended](https://github.com/golang/go/issues/101) in Golang, but they can still provide valuable documentation. In addition to having a GitHub page and a man page, a package should also provide parseable documentation for pkgsite. This enables Go users to access it through https://pkg.go.dev/github.com/darkhz/invidtui.

CC: @darkhz

**Comment by darkhz** [comment]
Documentation has already been implemented and hosted as a GitHub Pages website. Adding a man page will require a lot of effort, since the contents of the hosted documentation cannot be easily converted to roff/groff, and creating one from scratch is tedious work. I will consider this, however.
