### ISSUE TITLE
Almost black screen just after downloading audio

### ISSUE THREAD

**Issue by T0MuX** [darkhz/invidtui#24]
Hi, I'm sorry by advance if this is me not using well the application, but : just after started an audio only download the screen become almost full black, except the current song's progress bar. And when it does that, I'm totally unable to go back to the main window. I have to kill everything and launch invidtui again. Please, see the attached screenshots :
![1](https://user-images.githubusercontent.com/19415987/236331373-2708f63c-45c1-4036-ade8-7442894d623e.png)
![2](https://user-images.githubusercontent.com/19415987/236331378-3b1ad222-d1f8-47e8-a713-8812cc6ffe45.png)
![3](https://user-images.githubusercontent.com/19415987/236331382-90ec742d-3604-41e1-b07b-58c4cff4d8c1.png)

**Comment by T0MuX** [comment]
Hi, I just tested on another computer and have exactly the same issue.

**Comment by darkhz** [comment]
Noted. This is likely an internal issue, where on closing the download dialog the application switches to the wrong "page".
