### ISSUE TITLE
feed not working

### ISSUE THREAD

**Issue by r3k2** [darkhz/invidtui#28]
Hello, everytime I open invidtui my feed does not work until I log out and back into my instance again, then it works and shows the latest videos, not sure why is doing this, have anyone try this? or they just never log into a invidious instance with their subs channels? 
let me know because I love the program but is a pain in the ### to have to log out and in everytime so I end up back in freetube that I dont like because is a electron app and takes al lot of resources and does not way well with wayland/sway.

Thanks
PS: great program as soon I get this working I will use it and help

**Comment by darkhz** [comment]
Hmm, this is interesting. Can you mention the name of your instance, so that I can test it further?

- What is the type of authentication method/token that you have used? Is it a SID or a generated authentication token?
- How often do you have to log out of your instance? And when you say log out, do you mean logging out of your instance within a web browser?
- And when you say that your feeds don't work, do you mean that the feeds page/screen shows up empty?

I have tried it with the [instance](invidious.protokolla.fi) that I am logged into, and my feeds show up every time I open invidtui.

**Comment by r3k2** [comment]
Hello @darkhz  let me reply to your questions:

- 1. token method.
- 2. every day I try I want to log in only using invidtui but for troubleshooting I am using http/luakit , logging out I mean in invidutui not on the web.
- 3 yes it does shows up empty
- 4 the instance is https://vid.puffyan.us
I notice today that on https://vid.puffyan.us/token_manager I had 3 tokens, the one I use that shows on settings.json(bad because this token should be pick from pass/gopass or similar cli password manager) was there listed, so instead of loging out and in on invidtui what I did is delete one of the tokens from those 3, I open invidtuid and the feed did show up. will try again tomorrow and let you know, maybe is not comparing with all the tokens and picks the first one and if it does not match it will do something odd?

**Comment by darkhz** [comment]
Hmm, interesting. Have you tried using the SID instead? Token sessions may expire, which may be prompting you to log in multiple times.

Also, invidtui does not interact with the instance's token manager, other than to check if the user is authenticated. It uses whatever token you provide to it until the token has expired, so no comparing of tokens takes place.

On a further note, I will be fixing a bug where instance credentials are duplicated and stored.

**Comment by darkhz** [comment]
@r3k2 I have released a new update. Try regenerating your token with your instance, and see if the feed issue still persists.

**Comment by r3k2** [comment]
@darkhz thank you, I will try tonight when I get home from work.

**Comment by r3k2** [comment]
Hello I tried  did what you said, deleted the token, got a new one and added the new token so far I got it up and it shows the feed, will see tomorrow :) will let you know.
In a new issue I just notice I cant get to play any video with shift+v it says "Player: Unable to Play" any idea? I made usre youtube-dl was there and downloading and I use mpv already for everything...

**Comment by darkhz** [comment]
> Hello I tried  did what you said, deleted the token, got a new one and added the new token so far I got it up and it shows the feed, will see tomorrow :) will let you know.
> In a new issue I just notice I cant get to play any video with shift+v it says "Player: Unable to Play" any idea? I made usre youtube-dl was there and downloading and I use mpv already for everything... 

The unable to play error is likely due to your instance having issues, either check if your instance is loading media properly or switch to a different instance.

**Comment by r3k2** [comment]
Hello sorry took so long, being busy. I switched instance again and same result... unfortunately does not make sense for someone to be changing instances (meaning creating an account in that instance an again reimporting all the 200+ channel subscriptions) every time there is an issue :(  I use the same instance on FreeTube and no problem, but FreeTube is electron and I try to avoid that also I like CLI/TUI tools more.

**Comment by darkhz** [comment]
Ok, invidtui normally uses the `/latest_version` endpoint to load the media and this endpoint does not work for [vid.puffyan.us](https://vid.puffyan.us). I will issue a fix in the next release.

**Comment by darkhz** [comment]
@r3k2 I have a question, when you play from FreeTube, does it sometimes fallback to the local backend when the Invidious backend does not work? Do you see any error messages conforming to it?

If possible, can you record a demo video/gif of logging into your Invidious instance with both invidtui and FreeTube? Or perhaps record the point where you faced the error?

**Comment by darkhz** [comment]
This issue will be clo

**Comment by r3k2** [comment]
Hello @darkhz sorry for my late reply, I notice this is not an issue with invidtui (looks like) I changed instance to a better one like vid.puffyan.us and this does not happen. I have another issue now tho :( for some  time when I press V to view the video not do Q it it will just get stuck on "Loading"
