### ISSUE TITLE
REQUEST: Provide binaries also for 32 bit arm

### ISSUE THREAD

**Issue by m040601** [darkhz/invidtui#3]
Very nice and important that you remembered to provide precompiled binaries. Please keep it that way. Not everyone wants to constantly download 500 mega of Go just to test a project.

You already provide binaries for aarch64 (arm64). That's for example the Raspberry Pi 4 and 3 etc.

But you're leaving out a lot of perfectly capable devices, like the raspberry pi zero, 1 , 2 and a lot of arm chromebooks.

I'm not an expert in this. But as I see other projects doing, you only need to worry about 2 arm binaries:
- one for arm 64 bit, ( you do it already)
- one, and only one, for arm 32 bit (a "universal arm" for all the different armv6, armv7h, etc)
- 
I see that you're using goreleaser, and the process of building and releasing binaries seems be free and automated.  Go is such an easy peasy thing to compile for different platforms.So I assume this would be just a simple change without too much work.

Thanks in advance.

**Comment by darkhz** [comment]
Excellent suggestion, I will add arm32 to the list of compile targets in the next release

**Comment by darkhz** [comment]
@m040601 currently only armv6 binaries are supported, I forgot to add custom goarm requirements in the goreleaser configuration. I will do that in the next release.

**Comment by darkhz** [comment]
Fixed with v0.1.6
