### ISSUE TITLE
Cannot open menu with Alt+m

### ISSUE THREAD

**Issue by omnivagant** [darkhz/invidtui#32]
However, I managed with Esc+m, but that breaks a bit as Esc is also going back.

It would also be nice if you could choose menu with right and left arrows, as that would be more natural to me than Tab (and Shift+Tab to go the other direction didn't work either).

**Comment by darkhz** [comment]
Did you set any specific keybindings for the menu in the configuration? Sometimes some keybindings are not interpreted correctly by the terminal, can you check whether sending `Alt+m` works in general (i.e. in other programs, or by sending Ctrl-V)?

Also Shift-Tab is not implemented, to cycle through menu items you will have to use Tab for now. I will make menu movements modifiable in the coming releases.
