### ISSUE TITLE
NixOS package

### ISSUE THREAD

**Issue by rettetdemdativ** [darkhz/invidtui#33]
First of all, thanks for the work you invested into building this awesome program. I've been using it every day for weeks now and it's really good.

I took the freedom of [packaging](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/in/invidtui/package.nix) it for NixOS. I thought I'd let you know in case you wanted to link to the release or get involved in some way. Would you maybe want to add an **Installation** section or something mentioning the NixOS release? I could open a PR

**Comment by darkhz** [comment]
Thank you for packaging it for NixOS. I think it will already be reflected in the [repology](https://repology.org/project/invidtui/versions) page, so no other additions to the Installation page is required.

**Comment by alexmyczko** [comment]
Debian is also working on a package. Who is doing a brew for macOS?

**Comment by darkhz** [comment]
@alexmyczko No one has made/is making a brew for macOS, but it would be great if you could create one.
