### ISSUE TITLE
Thumbnail

### ISSUE THREAD

**Issue by Fries0202** [darkhz/invidtui#34]
Hello, congratulations on your project, it is very useful on old computers. I would like to know if there is any way to improve the thumbnail and also if there is any way to read the video description. I don't understand the subject, but I think we can discuss it, right?

**Comment by darkhz** [comment]
Yes, to view the video description and thumbnail you can press `Alt+Space` when the media is loaded and playing. Can you elaborate on what you mean by improving the thumbnail?
