### ISSUE TITLE
Add a 'go to' prompt to jump to specific timestamps during playback

### ISSUE THREAD

**Issue by Maytha8** [darkhz/invidtui#36]
My feature request is to add a keybinding that prompts the user for a timestamp, then jumps to it. 

It would help me get to the desired part of the audio/video faster than spamming the right arrow on my keyboard. :smile:

**Comment by darkhz** [comment]
Very good, this will be implemented.

**Comment by xplshn** [comment]
Also, this is more of a question, are URL's that point to a timestamp respected? As you probably know, Youtube lets you share URL's that when the other person clicks on them starts playback from the point at which you shared.

**Comment by darkhz** [comment]
As of now, no. The URIs are played irrespective of the timestamp. Playing from a specific timestamp could be implemented, however.

**Comment by xplshn** [comment]
Wonderful, thanks! Would be very much appreciated.

**Comment by darkhz** [comment]
https://github.com/darkhz/invidtui/assets/44058754/de7b7702-c520-42c2-95af-07a907ef5bd4

@Maytha8 this is what the new 'custom seeker' feature looks like.
Note that pressing 'Enter' will set the value to seek to.

**Comment by darkhz** [comment]
@xplshn the timestamp parsing is handled in another issue (#39).

**Comment by darkhz** [comment]
This is now implemented. Press the default keybinding <kbd>Alt</kbd>+<kbd>.</kbd> to display the custom seek dialog.
