### ISSUE TITLE
[Feature Request] Recommendations page?

### ISSUE THREAD

**Issue by xplshn** [darkhz/invidtui#38]
As the tittle says, support for YT's recommended page.
Based off of the approach used by YTFZF: https://github.com/pystardust/ytfzf/blob/master/addons/scrapers/recommended
Given that a POSIX sh could do it I am sure it could be implemented in less lines in Go.

Also, apps like Newpipe, somehow, have recommendations based off of the current video you are playing, I don't know the details behind such implementations, however, that'd be pretty cool and add to the entertainment/music listening experience. Thanks.

**Comment by darkhz** [comment]
Very good, this will be implemented.

**Comment by xplshn** [comment]
Thanks, this project is very handy! And more to me, I am the kind of person that has a bare .xinitrc script that only starts a terminal in full screen, and, in fact, I am writing this from a TUI Github client lol, anyways, thanks for this! Keep up the good work!

**Comment by darkhz** [comment]
@xplshn the question is, where would the recommended videos be displayed? Maybe it could be shown within the queue, in a separate space for recommended videos.

**Comment by xplshn** [comment]
Youtube has a recommendation page, and it also recommends videos inside of queues, the recommendations are different, the recommendations page is based on the videos you've watched in the past, and the recommended videos in a queue are based on what you watched on the past and what you are currently watching, so, I guess both?

**Comment by darkhz** [comment]
https://github.com/darkhz/invidtui/assets/44058754/3f5a1667-4588-4144-8045-7bc2b3bfcd49

This is how the current recommendations tab looks like.

**Comment by xplshn** [comment]
Wow, that's great! Any chance this project starts using Bubbletea, or FZF? In order to make the codebase smaller and also get sexier dialogs

**Comment by darkhz** [comment]
This is now implemented. Assuming that the default keybindings are set, press <kbd>q</kbd> to open the queue, and press <kbd>Tab</kbd> to switch between the 'Queue' and 'Recommendations' pages.
