### ISSUE TITLE
Stuck on Loading

### ISSUE THREAD

**Issue by r3k2** [darkhz/invidtui#44]
Hello, when I try to watch a video from my feed, it just get stuck on "Loading"
![swappy-20240514-170021](https://github.com/darkhz/invidtui/assets/5316229/108a9a2a-948d-409f-b31e-0443739d2f47)
I have deleted the config, relog into my instance with token and still problem persists..

**Comment by darkhz** [comment]
Did you try changing instances as well? Change an instance, open the queue and press enter on a queue item to reload it.

**Comment by r3k2** [comment]
i will try but if i change instance there i cant see my subs, i am using invitui to follow my channels rarely i need to search for other stuff. will try when i get home and let you know see if we can get to the button of this. thanks [edit[ oh wait i need it to let it sync lol ok so get the video in the Q then change instance and try to play it. got it

**Comment by r3k2** [comment]
@darkhz ok I did that same result when I press enter I get mpv: unable to load video or similar is super fast so cant read the whole thing.
![swappy-20240514-234916](https://github.com/darkhz/invidtui/assets/5316229/cbeffd2d-01cb-4c3a-b325-581b5ce31729)

**Comment by darkhz** [comment]
Try loading the stream manually:

- Press ';' on a video item to open the link popup, copy the invidious link.
- In another terminal, type `mpv <your invidious link>` and see if mpv actually plays it.

**Comment by r3k2** [comment]
@darkhz ok I did this, same  result :( 
![swappy-20240515-153356](https://github.com/darkhz/invidtui/assets/5316229/e4e2114e-cdaf-4d66-a0ef-ed867c54b0c7)
[edit] after a while waiting I got this error:
```
 mpv https://vid.puffyan.us/watch?v=BgzTAG_Vhn4
[ytdl_hook] ERROR: [youtube] BgzTAG_Vhn4: Video unavailable. This video is not available
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.
Exiting... (Errors when loading file)
```

**Comment by darkhz** [comment]
Ah, then this has something to do with the stream, youtube-dl or mpv.

**Comment by Leblake** [comment]
I've been having the same problem since around a month ago, and in my case, MPV is able to load videos correctly. However, and sadly, `invidtui` has stopped working for me. Every video/audio that I try to play fails with the message "MPV: unable to load [video name]". I just tried manually copying the Invidious link and opening it with MPV and it works.

**Comment by darkhz** [comment]
@Leblake can you provide the link of the invidious item which you are trying to play, so that I can test it as well?

**Comment by Leblake** [comment]
Here's the link: `https://iv.ggtyler.dev/watch?v=-_70t906txA`. Happens with all links, can't use `invidtui` anymore. :(

![image](https://github.com/darkhz/invidtui/assets/22378679/f2469123-caf9-4a94-86f7-cdf5c21b783a)

**Comment by darkhz** [comment]
The issue was found, apparently invidtui is using invalid parameters while sending files to MPV. A fix will be issued soon.

**Comment by Leblake** [comment]
Wow, that was lightning fast. Awesome work. :love_you_gesture:

**Comment by darkhz** [comment]
A quickfix has been released for now. This issue will be closed, and maybe later a status screen may be implemented, so that the user can monitor the stream that is currently being loaded, for potential errors, if any.
