### ISSUE TITLE
[bug]:  "Unable to load" a video

### ISSUE THREAD

**Issue by justchokingaround** [darkhz/invidtui#45]
i am unable to get any video to play on nixOS. i've tried building from source and also tried out the latest release, but unfortunately none worked for me. (i'm not sure if this is related to e9c4450460ba8084f02cca6cd0aeb3a4351787e3, but it seems like that didn't fix it)
![image](https://github.com/darkhz/invidtui/assets/44473782/0b639876-8cb1-498e-8be0-b55df383cb9e)

as you can see here, mpv is able to play the link that is displayed for a given video
![image](https://github.com/darkhz/invidtui/assets/44473782/1705cfee-0c17-47f5-929b-35f33e0fe43b)

**Comment by darkhz** [comment]
I'll take a look into it.

**Comment by darkhz** [comment]
@justchokingaround, how did you attempt to play the video exactly? Did you press 'a'/'v' on the media item?

**Comment by justchokingaround** [comment]
yep, i pressed `v`. but the same happens for `a` as well

**Comment by darkhz** [comment]
Okay, so apparently a particular endpoint in that instance (`local=true`) is disabled, that's why it doesn't return any media.
I'll issue a fix soon. Meanwhile you can try changing instances and loading media.

**Comment by justchokingaround** [comment]
i had the same issue with the couple other instances i tried

**Comment by darkhz** [comment]
@justchokingaround  In the second screenshot, MPV is able to play the video because it extracts all the media information from **YouTube** (yes, even though the URL provided is an Invidious URL), not exactly from the Invidious instance. That particular instance does not play some videos properly mainly because it contains outdated stream url data, when I tested it. Can you list the other instances you tried so that I can test those as well?

**Comment by justchokingaround** [comment]
yeah, i just tried out all of them, and i get that error for every single one of them. the only exception is `iv.melmac.space` for which i get a Media fetch error

**Comment by darkhz** [comment]
Even for `invidious.protokolla.fi`? It seems to be working for me. What is the exact error you get?

**Comment by justchokingaround** [comment]
![image](https://github.com/darkhz/invidtui/assets/44473782/ec4c6fcf-ee3b-44fb-9dbd-5c8838339121)
![image](https://github.com/darkhz/invidtui/assets/44473782/2375e28c-05cb-460e-b268-497805a7cc8d)

**Comment by darkhz** [comment]
Strange, it does work over here:
![image](https://github.com/darkhz/invidtui/assets/44058754/776d7d02-4c42-418c-9f93-087ceb506364)

Can you post your MPV version, and also try this command:
`mpv 'https://invidious.protokolla.fi/latest_version?id=xXlCcdPz6Vc&itag=139&local=true'`

**Comment by justchokingaround** [comment]
![image](https://github.com/darkhz/invidtui/assets/44473782/57f372f8-6aca-40c7-bfce-9b395fc6c96a)

**Comment by darkhz** [comment]
Can you try upgrading your MPV version to 0.38.0? There were some API changes in the latest version, and the latest commit adapts to those changes.

**Comment by justchokingaround** [comment]
this got fixed with mpv `0.38.0`. sorry for the late response, i completely forgot :pensive:
