### ISSUE TITLE
Don't set the background of the app

### ISSUE THREAD

**Issue by arthsmn** [darkhz/invidtui#46]
Currently the background of the app is set, so when using a transparent background terminal the app looks odd.

**Comment by darkhz** [comment]
@arthsmn can you post a screenshot? That would be helpful. Also if you haven't generated the theme file yet, generate it using the instructions in the `theme` branch of this repository.

**Comment by arthsmn** [comment]
A preview of the problem:
![2024-07-06T06:41:01,477830932-03:00](https://github.com/darkhz/invidtui/assets/150680976/c033a7c6-97f4-43c6-8197-69ebab7389f9)
![2024-07-06T06:41:09,363207439-03:00](https://github.com/darkhz/invidtui/assets/150680976/2df5d200-3775-4d21-8cda-df3ceca6379e)
![2024-07-06T06:41:12,870338380-03:00](https://github.com/darkhz/invidtui/assets/150680976/6d1fa173-549a-48ab-ab3d-f77ef67d1d76)

As you can see, first my terminal isn't setting a background color, so it is blurred. When selecting the instance, it's still blurred. But, when the app opens the background is set to black, which overwrites the blur.

**Comment by darkhz** [comment]
Ok, A small fix has been issued now. Install the latest version first.

For background transparency:
- If you don't have the `themes` directory within your config folder (\~/.config/invidtui for example), do `invidtui ---generate` first. A **themes** directory with a **default.theme** file will be generated. (\~/.config/invidtui/themes/default.theme for example) 
- Now, open the **default.theme** file, edit the `Background` property to `bg:default` within the `App` context. It should look like this:
```
...
{ 
  App: {                       
    Author: attr:bold; fg:purple
    Background: bg:default
    Border: attr:bold; fg:white
    FormButton: attr:bold; bg:blue; fg:white
...
```
- Save the file, and relaunch invidtui.

For theming any other properties, refer to the [themes](https://github.com/darkhz/invidtui/tree/theme) branch.

**Comment by arthsmn** [comment]
This works, thanks!
