### ISSUE TITLE
Feature request: Subscription feed

### ISSUE THREAD

**Issue by AaronStiff** [darkhz/invidtui#8]
Wondering whether a subscription feed would ever be added?

I'm unfamiliar with Go and new to Linux, but somehow I got Invidtui running. :) So cool that I can browse Invidious in the terminal, but I can't completely switch over since there's no way to check a list of channels I've "subscribed" to. Is that feature on the horizon? :)

Also, a question: are videos being proxied through an Invidious instance, and if not, is there a way to force that?

**Comment by ghost** [comment]
To subscribe to YouTube channels, you can use [newsboat](https://github.com/newsboat/newsboat). 

After installing newsboat go to .newsboat folder and create a file named urls. Then you put your YouTube suscriptions in this format: https://www.youtube.com/feeds/videos.xml?channel_id=here you put channel id ~Channelname tag1 tag2 

You can use tags to filter the results you want (see query feeds in newsboat). You can open the videos with firefox or mpv or with a custom video player. 
The only thing I do not know, and I also would like to know, is how to send through invidious my feeds when opening them with newsboat through mpv player. Currently, if I want my feeds to go through invidious I open them with the browser, and then they are proxied through invidious thanks to this addon: [libredirect](https://github.com/libredirect/libredirect).

**Comment by AaronStiff** [comment]
Many thanks! I will definitely look into this.

**Comment by AaronStiff** [comment]
@bambirombi

I believe if you add this line to your newsboat config file:

```browser "<terminal-name> -e invidtui --search-video %u"```

then the video will open through invidtui after pressing `o` while in a selection.

The only catch is that `<terminal-name>` must be a different terminal than the one you are using. I tried several things to get my terminal (Konsole) to open invidtui in a new window, but I failed to find a solution.

**Comment by ghost** [comment]
@AaronStiff I tried but did not work. How have you set the macro to open with "o"?

**Comment by AaronStiff** [comment]
I believe that is just the default keybinding:

https://newsboat.org/releases/2.28/docs/newsboat.html#_first_ui_interaction

**Comment by darkhz** [comment]
Viewing subscriptions will require authentication with invidious, a feature that I haven't implemented in invidtui. It is planned, however. I'll have it implemented natively in invidtui in the future releases.

**Comment by elig0n** [comment]
Besides invidious subs. that require authentication what do you think about implementing local subs. ?

**Comment by AaronStiff** [comment]
Honestly I'd prefer local subs myself!

**Comment by darkhz** [comment]
Subscriptions, playlists and feed can now be viewed in the dashboard after authenticating with an invidious instance. Local subs will take a little time to implement. I am closing this issue since subscription feature is implemented, but if you have any issues, create a new issue referencing the dashboard implementation instead.
