### ISSUE TITLE
[Bug] Audio not working by default

### ISSUE THREAD

**Issue by ghost** [darkhz/invidtui#9]
The audio mode does not work. I can see that it starts playing 
![image](https://user-images.githubusercontent.com/87095035/179519909-5f16a870-a893-41f0-a342-009276c2b79d.png)
but I cannot hear anything. 

The same happens with the video. By default, it is muted, and I have to unmute it. So, anyway of changing the default behavior?

invidtui version: 0.2.1-2
arch linux

**Comment by darkhz** [comment]
Hmm, the player states(shuffle, mute, etc.) are usually saved on exit and restored on startup, i.e, if you muted the audio/video stream, and then exited the application, the mute state will be restored the next time you start invidtui. Does this happen regardless of whether you set the mute state or not? Can you check the contents of `~/.config/invidtui/state`?

I will try reproducing this issue on my end.

**Comment by ghost** [comment]
This is what I have in `~/.config/invidtui/state`: volume 100,shuffle

**Comment by darkhz** [comment]
@bambirombi hmm, the mute command isn't present in your state file, therefore invidtui shouldn't set the mute state on startup. Can you re-verify if the mute state is set now on startup? If it is, I'll look into it.

**Comment by ghost** [comment]
@darkhz It works correctly. It was my fault.
